name: Go CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Tests
        working-directory: BGP
        run: go test -v ./...

      - name: Build Linux Binary
        working-directory: BGP
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" -o dist/bgp-linux-amd64 .


      - name: Build Windows Binary
        working-directory: BGP
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/bgp-windows-amd64.exe .

      - name: Build macOS Binary
        working-directory: BGP
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/bgp-darwin-amd64 .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bgp-builds
          path: BGP/dist/
